services:
  - type: web
    name: packers-movers-website
    env: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT web.php
    envVars:
      - key: PORT
        value: 8000